---

- name: Deploy PHP-FPM 8.2 pool
  ansible.builtin.template:
    src: "php_82.j2"
    dest: '/etc/php/8.2/fpm/pool.d/{{ dropfactory_platform_unix_user }}.conf'
    mode: "0640"
  notify: Reload php8.2-fpm
  tags:
    - php_pool
