doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrationsRemote': '%kernel.project_dir%/migrationsRemote'
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
    em: default
