---

- name: Create site
  ansible.builtin.shell:
    chdir: "~{{ dropfactory_site_platform_user }}/platform/"
    cmd: "umask 027; ~/platform/vendor/bin/drush site:install --sites-subdir='{{ dropfactory_site_domain[0] }}' --db-url='mysql://{{ dropfactory_site_db }}:{{ dropfactory_site_db_password.stdout }}@localhost/{{ dropfactory_site_db }}?module=mysql#drupal-{{ dropfactory_site_id }}_' --yes"
  become: true
  become_user: "{{ dropfactory_site_platform_user }}"
