
- name: Reset admin password
  ansible.builtin.shell:
    chdir: "~{{ dropfactory_site_platform_user }}/platform/web/sites/{{ dropfactory_site_domain[0] }}"
    cmd: "umask 027; ~/platform/vendor/bin/drush user:login"
  become: true
  become_user: "{{ dropfactory_site_platform_user }}"
  register: output
